version: "3.3"

services:
  oraclelocal:
    container_name: oraclelocal
    image: container-registry.oracle.com/database/standard
    ports:
      - "1527:1521"
      - "5507:5500"
    volumes:
      - ./utplsql/source:/opt/oracle/utplsql:rw
    shm_size: 8g